/** Unicode nativo: nessun download o servizio esterno per le emoji. */
export const EMOJI_GROUPS = [
  {
    name: "Reazioni",
    items: [
      ["😂", "Risata"],
      ["🤣", "Ridere tantissimo"],
      ["😭", "Pianto"],
      ["🥹", "Commosso"],
      ["😍", "Innamorato"],
      ["🥰", "Affetto"],
      ["🤩", "Entusiasta"],
      ["😎", "Forte"],
      ["😱", "Sorpresa"],
      ["🤯", "Incredibile"],
      ["🫠", "Mi sciolgo"],
      ["💀", "Morto dal ridere"],
      ["😅", "Risata nervosa"],
      ["🙂", "Sorriso"],
      ["🙃", "Ironia"],
      ["😉", "Occhiolino"],
      ["🤔", "Pensieroso"],
      ["🫡", "Rispetto"],
      ["🤨", "Dubbio"],
      ["😤", "Frustrato"],
      ["😡", "Arrabbiato"],
      ["🥱", "Noia"],
      ["😴", "Sonno"],
      ["🤢", "Disgusto"],
    ],
  },
  {
    name: "Gesti e cuori",
    items: [
      ["❤️", "Cuore"],
      ["🧡", "Cuore arancione"],
      ["💛", "Cuore giallo"],
      ["💚", "Cuore verde"],
      ["💙", "Cuore blu"],
      ["💜", "Cuore viola"],
      ["🖤", "Cuore nero"],
      ["💔", "Cuore spezzato"],
      ["❤️‍🔥", "Cuore in fiamme"],
      ["🫶", "Mani a cuore"],
      ["👏", "Applausi"],
      ["🙌", "Evviva"],
      ["👍", "Mi piace"],
      ["👎", "Non mi piace"],
      ["🤌", "Gesto italiano"],
      ["🤝", "Accordo"],
      ["🙏", "Grazie"],
      ["💪", "Forza"],
    ],
  },
  {
    name: "Cinema e altro",
    items: [
      ["🎬", "Cinema ciak"],
      ["🍿", "Popcorn"],
      ["🎥", "Film"],
      ["📺", "Serie televisione"],
      ["🎭", "Teatro dramma"],
      ["🏆", "Premio"],
      ["⭐", "Stella"],
      ["🔥", "Fuoco"],
      ["✨", "Scintille"],
      ["💯", "Cento perfetto"],
      ["🎉", "Festa"],
      ["🎶", "Musica"],
      ["👀", "Occhi"],
      ["🧠", "Cervello"],
      ["🚀", "Razzo"],
      ["👑", "Corona"],
      ["🐐", "Capra goat migliore"],
      ["🌈", "Arcobaleno"],
    ],
  },
] as const;
