/**
 * Le keyword di TMDB sono in inglese e non esiste una traduzione italiana
 * nell'API. Mostrarle così com'è sarebbe contro la regola della lingua del
 * progetto, quindi il motivo di un consiglio si scrive solo quando la keyword sta
 * in questo dizionario: sono le etichette di filone più frequenti, tradotte a mano.
 * Una keyword senza traduzione continua a *pesare* nel punteggio — semplicemente non
 * compare come motivo.
 */

export const KEYWORD_LABELS: Record<string, string> = {
  // Struttura e trama
  heist: "Rapina",
  "time loop": "Loop temporale",
  "time travel": "Viaggio nel tempo",
  revenge: "Vendetta",
  survival: "Sopravvivenza",
  "coming of age": "Crescita",
  "road movie": "Viaggio",
  "one night": "Una notte sola",
  "double life": "Doppia vita",
  investigation: "Indagine",
  "serial killer": "Serial killer",
  kidnapping: "Rapimento",
  heartbreak: "Amore finito",
  "love triangle": "Triangolo amoroso",
  friendship: "Amicizia",
  "family relationships": "Famiglia",
  "father son relationship": "Padre e figlio",
  "mother daughter relationship": "Madre e figlia",
  siblings: "Fratelli",
  betrayal: "Tradimento",
  redemption: "Redenzione",
  obsession: "Ossessione",
  "coming out": "Coming out",
  addiction: "Dipendenza",
  grief: "Lutto",
  "mental illness": "Malattia mentale",
  "small town": "Provincia",
  "culture clash": "Scontro di culture",

  // Genere e ambientazione
  dystopia: "Distopia",
  "post-apocalyptic future": "Post apocalisse",
  "space opera": "Space opera",
  "outer space": "Spazio",
  spaceship: "Astronave",
  "artificial intelligence": "Intelligenza artificiale",
  robot: "Robot",
  cyberpunk: "Cyberpunk",
  "alternate reality": "Realtà alternativa",
  "parallel world": "Mondo parallelo",
  "virtual reality": "Realtà virtuale",
  "alien invasion": "Invasione aliena",
  extraterrestrial: "Alieni",
  zombie: "Zombie",
  vampire: "Vampiri",
  werewolf: "Licantropi",
  witch: "Streghe",
  ghost: "Fantasmi",
  "haunted house": "Casa infestata",
  exorcism: "Esorcismo",
  "cosmic horror": "Horror cosmico",
  "body horror": "Body horror",
  "found footage": "Found footage",
  slasher: "Slasher",
  "home invasion": "Invasione domestica",
  monster: "Mostri",
  kaiju: "Kaiju",
  dinosaur: "Dinosauri",
  dragon: "Draghi",
  magic: "Magia",
  wizard: "Maghi",
  superhero: "Supereroi",
  supervillain: "Supercattivi",
  "secret identity": "Identità segreta",
  "martial arts": "Arti marziali",
  samurai: "Samurai",
  ninja: "Ninja",
  western: "Western",
  pirate: "Pirati",
  "medieval times": "Medioevo",
  "ancient rome": "Antica Roma",
  "world war ii": "Seconda guerra mondiale",
  "world war i": "Prima guerra mondiale",
  "vietnam war": "Guerra del Vietnam",
  "cold war": "Guerra fredda",
  holocaust: "Olocausto",
  "nazi germany": "Germania nazista",
  war: "Guerra",
  military: "Militari",
  espionage: "Spionaggio",
  spy: "Spie",
  cia: "CIA",
  assassin: "Sicari",
  hitman: "Sicari",
  mafia: "Mafia",
  gangster: "Gangster",
  "organized crime": "Criminalità organizzata",
  "drug cartel": "Cartello della droga",
  "drug trafficking": "Traffico di droga",
  prison: "Carcere",
  "police corruption": "Polizia corrotta",
  detective: "Detective",
  "private investigator": "Investigatore privato",
  courtroom: "Aula di tribunale",
  lawyer: "Avvocati",
  hospital: "Ospedale",
  doctor: "Medici",
  "high school": "Liceo",
  college: "Università",
  teacher: "Insegnanti",
  journalism: "Giornalismo",
  politics: "Politica",
  "wall street": "Finanza",
  corporate: "Aziende",
  heiress: "Ereditiere",
  royalty: "Reali",
  "true crime": "Cronaca nera",
  cult: "Sette",
  religion: "Religione",
  nuclear: "Nucleare",
  pandemic: "Pandemia",
  "climate change": "Clima",
  "natural disaster": "Catastrofe naturale",
  shipwreck: "Naufragio",
  mountain: "Montagna",
  desert: "Deserto",
  jungle: "Giungla",
  island: "Isola",
  "road trip": "Viaggio in auto",
  "car chase": "Inseguimenti",
  racing: "Corse",
  boxing: "Pugilato",
  football: "Calcio",
  basketball: "Basket",
  sport: "Sport",
  music: "Musica",
  band: "Band",
  rockstar: "Rockstar",
  dance: "Danza",
  chef: "Cucina",
  fashion: "Moda",
  art: "Arte",
  writer: "Scrittori",
  hollywood: "Hollywood",
  "show business": "Spettacolo",
  "based on play or musical": "Dal teatro",
  biography: "Biografia",
  "historical figure": "Personaggio storico",
  documentary: "Documentario",
  "black comedy": "Commedia nera",
  satire: "Satira",
  parody: "Parodia",
  "buddy comedy": "Coppia comica",
  "romantic comedy": "Commedia romantica",
  christmas: "Natale",
  wedding: "Matrimonio",
  "dysfunctional family": "Famiglia disfunzionale",
  "single parent": "Genitore solo",
  adoption: "Adozione",
  pregnancy: "Gravidanza",
  "coming home": "Ritorno a casa",
  immigration: "Immigrazione",
  racism: "Razzismo",
  lgbt: "LGBT",
  feminism: "Femminismo",
  "class differences": "Differenze di classe",
  poverty: "Povertà",
  "small business": "Piccola impresa",
  "con artist": "Truffatori",
  gambling: "Gioco d'azzardo",
  "bank robbery": "Rapina in banca",
  "money laundering": "Riciclaggio",
  hacker: "Hacker",
  conspiracy: "Complotto",
  "government conspiracy": "Complotto di stato",
  amnesia: "Amnesia",
  "split personality": "Doppia personalità",
  dream: "Sogni",
  nightmare: "Incubi",
  "psychological thriller": "Thriller psicologico",
  "chosen one": "Il prescelto",
  prophecy: "Profezia",
  quest: "Missione",
  treasure: "Tesoro",
  "secret society": "Società segreta",
  school: "Scuola",
  teenager: "Adolescenti",
  childhood: "Infanzia",
  "old age": "Vecchiaia",
  dog: "Cani",
  horse: "Cavalli",
  animal: "Animali",
  space: "Spazio",
  astronaut: "Astronauti",
  moon: "Luna",
  mars: "Marte",
  apocalypse: "Apocalisse",
  "end of the world": "Fine del mondo",
};

/** L'etichetta italiana di una keyword, o `null` se non la sappiamo tradurre. */
export function keywordLabel(name: string): string | null {
  return KEYWORD_LABELS[name.trim().toLowerCase()] ?? null;
}
